language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - pip install --use-mirrors -r requirements_dev.txt
    - pip install --use-mirrors coverage
script:
    - nosetests --with-coverage --cover-package=giiit --verbose giiit_tests/
